[project]
name = "mnist-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.2.0",
    "equinox>=0.11.11",
    "jax>=0.4.38",
    "optax>=0.2.4",
    "pillow>=11.1.0",
]
